[package]
name = "microbit-playground"
version = "0.1.0"
authors = ["Jeremy Stucki <dev@jeremystucki.ch>"]
edition = "2018"

[dependencies]
cortex-m = "0.6"
cortex-m-rt = "0.6"
bare-metal = "0.2"

nrf51-hal = "0.7"

heapless = "0.5"
