[package]
name = "microbit-scrolling-display"
version = "0.1.0"
authors = ["Jeremy Stucki <dev@jeremystucki.ch>"]
edition = "2018"

[dependencies]
nrf51-hal = "0.7"
bare-metal = "0.2"
heapless = "0.5"
cortex-m = "0.6"
cortex-m-rt = "0.6"
microbit-simple-display = { path = "../simple-display" }
